# Generated by Django 3.2.7 on 2023-01-07 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_agenda_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='telefono',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
